config/routes.rb
ReadSupport::Application.routes.draw do
root :to => 'books#index'
  
  resources :scenes
  resources :books

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :scenes ,:dependent => :destroy
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @book = Book.new

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :category, :label, :year, :outline, :memo)
    end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
    @books = Book.find(:all).map{|i|
      [i.title,i.id]
    }
  end

  # GET /scenes/1/edit
  def edit
  @books = Book.find(:all).map{|i|
      [i.title,i.id]
    }
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene.book, notice: 'Scene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scene }
      else
        format.html { render action: 'new' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:book_id, :title, :outline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :outline %><br>
    <%= f.text_area :outline %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>BookList</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Category</th>
      <th>Label</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.category %></td>
        <td><%= book.label %></td>
        <td><%= book.year %></td>
        <td><%= link_to '詳細', book %></td>
        <td><%= link_to '編集', edit_book_path(book) %></td>
        <td><%= link_to '消去', book, method: :delete, data: { confirm: '本当によろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= render 'form' %>

<%= link_to '本を追加する', new_book_path %>
<%= link_to 'シーン一覧へ', scenes_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Label:</strong>
  <%= @book.label %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Outline:</strong>
  <%= @book.outline %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @book.memo %>
</p>

<hr>
<hr>
<b>シーン一覧</b>

<table>
<thead>
<tr>
  <th>Title</th>
  <th>outline</th>
  <th></th>
  <th></th>
  <th></th>
</tr>
</thead>
<tboby>
<% if @book.scenes %>
<% for det in @book.scenes %>
<tr>
  <td><%= det.title %></td>
  <td><%= det.outline %></td>
  <td><%= link_to '詳細', det %></td>
  <td><%= link_to '編集', edit_scene_path(det) %></td>
  <td><%= link_to '消去', det, method: :delete, data: { confirm: '消去してよろしいですか？'} %></td>
</tr>
<% end %>
<% end %>
</tbody>
</table>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
<%= link_to 'シーン追加', new_scene_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadSupport</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book %><br>
    <%= f.select :book_id, @books %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :outline %><br>
    <%= f.text_area :outline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Title</th>
      <th>Outline</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><% if scene.book %>
	  <%= scene.book(force_reload = false).title %>
	<% end %></td>
        <td><%= scene.title %></td>
        <td><%= scene.outline %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Scene', new_scene_path %>
<%= link_to '本一覧', books_path %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @scene.book(force_reload = false).title %>
</p>

<p>
  <strong>Title:</strong>
  <%= @scene.title %>
</p>

<p>
  <strong>Outline:</strong>
  <%= @scene.outline %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to '本の詳細ページへ', book_path(@scene.book_id) %>